### ISSUE TITLE
Domain not pulled into output text

### ISSUE THREAD

**Issue by wintercooled** [valerio-vaccaro/liquid-faucet#1]
Issuing an asset - the domain was not pulled through to the output text:

I entered a domain of "wintercooled.github.io" and after issuance the output was:

`{"entity":{"domain":null},"issuer_pubkey":"02975e0994cae5435718690277d4822001367d7df3f2538177578b86d64428afa9","name":"Liquid Testnet Asset Test","precision":"0","ticker":"LTN","version":0}`
             
`If you want register this asset create a file on https://None/.well-known/liquid-asset-proof-22ff5026f0ec9b999ab8552fd97c74d00fd2d110bb33de50954c4cb6758f3a6e with content`

`Authorize linking the domain name None to the Liquid asset 22ff5026f0ec9b999ab8552fd97c74d00fd2d110bb33de50954c4cb6758f3a6e`

**Comment by valerio-vaccaro** [comment]
solved in https://github.com/valerio-vaccaro/liquid-faucet/commit/01b8320f79f1f298590f9be412c7736b4d8d6fba
